---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgAOct71ePSrsSuZwUTAN49LOSPEkXlmNnCEKeLA7UWDOrFf5glz0dbbuOJPdWKM7EEe1fw7kEDrcenCnHC/W1f2wfIi3pO5ASFgen3+GPHAIrBs/HVrLUqYb2ffRnG9axjLidgSU3w0REBwskDe9mX1bcnv8IVttRxLuAWMAWti5InwarFmPfyTOKbNGP5RbEbmEikJ+8kFdl5GTQnkOJSXx/EjM7wsMSMTvr+lFXUKe6ceQhq/SFKwClUQyJutvpwt8cjkeVoAko/vHAtGPAxe6YnDUDFgYu9pJ1o+c887HtHm+UT8WaBnGuNkp+Hr4r5Sv55BBBJpvp5QHa2IZzoJqZHv/j7d9A09LV4k6Gv4B1m0dP4S0bXgiiHDFZwblmKQaKreALI0vlYiW1WTg1cH+F8pz6Tzww+dcG3tdDlceqKlTA1nExfF8cX7V6d6vwZ5B1Gs7yJDt52hoDwV9X0CJfYFGKPnaVDMiLI2aLt4TQkgxP4SGscfUBDCCV1tB6ZpFHf0NoL/PLVSEc3wmksmqaOzSnMbCvH5mCQ9KXTzR5QT0+y+EMHsc5h+7JuSIE48NBqSelbYzi1AWt+3aQLP7RCicNbbcfpsP8fy56+Uub8uaIVkqTNjijiNK0YUcvdoqfT15VTvW6WjcaHJJxJmBks9sqetb2PVwrNa6BRPDLxqViFD6ytTJkUw4zEtspvPZACEMebWozqWTOBhMXrBDFyKXU28EBh/ijb9jWrIYHVz
    STRIPE_API_KEY: AgCa08URg9cY8uF4XOi/MOqrToeEzeEWI08ouGwU+Kz8Egs8vVUfFtdaWeNxblDKXbD84BSc2uQeauHQxek3VnM7WqNWJvh4dt9teXYCh3R9vvvVOifSdi7Lkzft+fSXqY5qXEuxvCh5YPNfE7skNoABAZjD68apzVnVgFomt8nW23WcN15WvSecnRruU6Nfr6WxDwP+syI+Mmvo1iXB3eaL792zGsyucd97x/AezpfNsvpEcXqiRyR8LOy2B+exjzyhzrI8zMpocEUsYptMiu91XBg+ka/512o2HGpCNJSQJwbrFTkzD0f/bgFRYR/+OQeu2y7MyB7O/xbIGRLt62Z/UHUEnNe2DtB19OXe/4MEIi+sl/T7sV+CDOU7ZaClMA1kJVMIVw4DJZGCxeIKdtGK6KJbIysztYbyh7iXyAt1Gv9QN8d5PuNuFQQFMUTzQbwkqZF/Omo/TO3D/ELO62tzZg/FS7E23sd4HvgkuMfp8kVAPscrGhlyt67eh2VfHmJD4EzCaPqNl7N1fux5no22kQTZ+OMvkUcLv1/DVQ3XsxxID/CfRNRKTua+Eylb/7QxdQ69Y0U+GfCOB5pbWQrdY2CPRGJBggF6J1hcTBj0bz9W0zBFbvT642hlvcC8f3CQOzxk6PLEx8fDEP4kc8n9+EXQv8rELYiTlkwo86Kmu+grGmqhsdi6niePU37r+Gm8Zc4vo435yocvPooQ8V/nf/hM82ef1R91xrMRIzXeWQ==
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
